package com.sicau.entity.dto;

public class ModificationTeam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modification_team.modification_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String modificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modification_team.team_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modification_team.modification_type
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String modificationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modification_team.modification_content
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String modificationContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modification_team.state
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modification_team.modification_place
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String modificationPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modification_team.original_data
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String originalData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modification_team.modification_id
     *
     * @return the value of modification_team.modification_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getModificationId() {
        return modificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modification_team.modification_id
     *
     * @param modificationId the value for modification_team.modification_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setModificationId(String modificationId) {
        this.modificationId = modificationId == null ? null : modificationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modification_team.team_id
     *
     * @return the value of modification_team.team_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modification_team.team_id
     *
     * @param teamId the value for modification_team.team_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modification_team.modification_type
     *
     * @return the value of modification_team.modification_type
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getModificationType() {
        return modificationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modification_team.modification_type
     *
     * @param modificationType the value for modification_team.modification_type
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setModificationType(String modificationType) {
        this.modificationType = modificationType == null ? null : modificationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modification_team.modification_content
     *
     * @return the value of modification_team.modification_content
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getModificationContent() {
        return modificationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modification_team.modification_content
     *
     * @param modificationContent the value for modification_team.modification_content
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setModificationContent(String modificationContent) {
        this.modificationContent = modificationContent == null ? null : modificationContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modification_team.state
     *
     * @return the value of modification_team.state
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modification_team.state
     *
     * @param state the value for modification_team.state
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modification_team.modification_place
     *
     * @return the value of modification_team.modification_place
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getModificationPlace() {
        return modificationPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modification_team.modification_place
     *
     * @param modificationPlace the value for modification_team.modification_place
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setModificationPlace(String modificationPlace) {
        this.modificationPlace = modificationPlace == null ? null : modificationPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modification_team.original_data
     *
     * @return the value of modification_team.original_data
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getOriginalData() {
        return originalData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modification_team.original_data
     *
     * @param originalData the value for modification_team.original_data
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setOriginalData(String originalData) {
        this.originalData = originalData == null ? null : originalData.trim();
    }
}