package com.sicau.entity.dto;

public class Team {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_name
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.direction
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String direction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.description
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.create_time
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_state
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String teamState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.team_score
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String teamScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.number
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.team_id
     *
     * @return the value of team.team_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.team_id
     *
     * @param teamId the value for team.team_id
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.team_name
     *
     * @return the value of team.team_name
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.team_name
     *
     * @param teamName the value for team.team_name
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.direction
     *
     * @return the value of team.direction
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.direction
     *
     * @param direction the value for team.direction
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.description
     *
     * @return the value of team.description
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.description
     *
     * @param description the value for team.description
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.create_time
     *
     * @return the value of team.create_time
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.create_time
     *
     * @param createTime the value for team.create_time
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.team_state
     *
     * @return the value of team.team_state
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getTeamState() {
        return teamState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.team_state
     *
     * @param teamState the value for team.team_state
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setTeamState(String teamState) {
        this.teamState = teamState == null ? null : teamState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.team_score
     *
     * @return the value of team.team_score
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getTeamScore() {
        return teamScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.team_score
     *
     * @param teamScore the value for team.team_score
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setTeamScore(String teamScore) {
        this.teamScore = teamScore == null ? null : teamScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.number
     *
     * @return the value of team.number
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.number
     *
     * @param number the value for team.number
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }


}