package com.sicau.dao;

import com.sicau.entity.dto.ModificationTeam;

import java.util.List;

public interface ModificationTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modification_team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    int deleteByPrimaryKey(String modificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modification_team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    int insert(ModificationTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modification_team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    ModificationTeam selectByPrimaryKey(String modificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modification_team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    List<ModificationTeam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modification_team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    int updateByPrimaryKey(ModificationTeam record);

    /**
     * 团队修改审核
     * @param modificationTeam
     * @return
     */
    int updateStateByPrimaryKey(ModificationTeam modificationTeam);
}