package com.sicau.dao;


import java.util.List;

import com.sicau.entity.dto.Team;
import com.sicau.entity.pojo.po.AuditedTeamPO;
import org.apache.ibatis.annotations.Param;

public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    int deleteByPrimaryKey(String teamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    Team selectByPrimaryKey(String teamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    List<Team> selectAll();
    /**
     * 查找待审核团队
     * 
     * @return
     */
    List<AuditedTeamPO> selectAuditedTeam();
    
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbg.generated Fri Feb 01 16:05:07 CST 2019
     */
    int updateByPrimaryKey(@Param("state") Team record);
    /**
     * @param teamId 团队ID
     * @param score 分数
     * @return int 返回更新影响的行数
     * @author Lee
     * @description 更新团队的分数信息
     * @date 2019/2/8
     */
    int updateScore(@Param("teamId") String teamId,@Param("score") String score);
    /**
     * @param teamId :团队ID
     * @return com.sicau.entity.dto.Team
     * @author Lee
     * @description :获取Team对象
     * @date 2019/2/8
     */
    Team getTeam(@Param("teamId") String teamId);

    Team selectTeamById(@Param("teamId") String teamId);

    boolean updateStateTeam(@Param("teamId") String teamId,@Param("state") String state);
}